object Versions {
    const val androidLibrary = "7.3.1"
    const val kotlin = "1.6.10"
    const val compose = "1.1.1"
    const val coreKtx = "1.7.0"
    const val lifecycleRuntime = "2.3.1"
    const val activityCompose = "1.3.1"
    const val material = "1.0.0-alpha02"
    const val retrofit = "2.9.0"
    const val guava = "31.1-android"
    const val simpleXml = "2.7.1"
    const val jUnit = "4.13.2"
    const val jUnitExt = "1.1.4"
    const val espresso = "3.5.0"
    const val hilt = "2.42"
    const val hiltCompiler = "1.0.0"
}